//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOrg
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectOrganizationEntities : DbContext
    {

        private static ProjectOrganizationEntities _context;

        public static ProjectOrganizationEntities GetContecxt()
        {
            if (_context == null)
                _context = new ProjectOrganizationEntities();
            return _context;
        }

        public ProjectOrganizationEntities()
            : base("name=ProjectOrganizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTRACT> CONTRACT { get; set; }
        public virtual DbSet<DEPARTAMENT> DEPARTAMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<ORGANIZATION> ORGANIZATION { get; set; }
        public virtual DbSet<PROJECT> PROJECT { get; set; }
    }
}
