//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOrg
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        public int Project_ID { get; set; }
        public int Contract_ID { get; set; }
        public int Departament_ID { get; set; }
        public string ProjectName { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public decimal ProjectCost { get; set; }
        public string ProjectPhoto { get; set; }

        public string start
        {
            get
            {
                return Start_Date.ToShortDateString();
            }
        }
        public string end
        {
            get
            {
                if (End_Date.HasValue)
                    return "Дата окончания: " + End_Date.Value.ToShortDateString(); // Используем Value для доступа к DateTime
                else
                    return ""; // Возвращаем пустую строку, если значение отсутствует
            }

        }



        public virtual CONTRACT CONTRACT { get; set; }
        public virtual DEPARTAMENT DEPARTAMENT { get; set; }
    }
}
